/**
 * Type system for the Health Canada DEL Readiness Assessment (Prompt 20).
 *
 * Three concept layers:
 *
 *   1. **Rubric** — the canonical definition of categories + questions +
 *      option weights. Hardcoded in `rubric.ts` for v1; migrates to a
 *      Sanity `delReadinessRubric` document at Prompt 22.
 *
 *   2. **Answers** — what the user submits. A flat map of `questionId →
 *      optionId`. The form's branching logic (showWhen) only affects which
 *      questions are *rendered*, not the answer shape.
 *
 *   3. **Assessment** — the structured output. Score is computed
 *      deterministically from the rubric + answers in `score.ts`; gaps +
 *      remediation are generated by the model via a single `recommend`
 *      tool call.
 *
 * Keeping all three locked to one Zod schema means the route, the
 * deterministic scorer, the AI tool's `parameters`, and the client preview
 * never disagree on shape.
 */
import { z } from "zod";

/* -------------------------------------------------------------------------- */
/*  Categories                                                                 */
/* -------------------------------------------------------------------------- */

export const CATEGORY_IDS = [
  "facility",
  "qms",
  "personnel",
  "site-master-file",
  "gdp",
  "import-export",
  "cold-chain",
] as const;

export const CategoryIdSchema = z.enum(CATEGORY_IDS);
export type CategoryId = z.infer<typeof CategoryIdSchema>;

export const RubricCategorySchema = z.object({
  id: CategoryIdSchema,
  label: z.string().min(2).max(80),
  description: z.string().min(2).max(280),
  /** Category weight 0–100. The full rubric's category weights sum to 100. */
  weight: z.number().int().min(1).max(60),
});
export type RubricCategory = z.infer<typeof RubricCategorySchema>;

/* -------------------------------------------------------------------------- */
/*  Questions + options                                                        */
/* -------------------------------------------------------------------------- */

export const QuestionOptionSchema = z.object({
  id: z.string().min(1).max(60),
  label: z.string().min(2).max(160),
  /**
   * Option completeness weight, 0–1. Used by `score.ts`:
   *   1.0 = fully in place
   *   0.5 = partially in place / in progress
   *   0.0 = not in place / not applicable to a positive score
   * Helper text lives on the rubric question, not the option.
   */
  weight: z.number().min(0).max(1),
});
export type QuestionOption = z.infer<typeof QuestionOptionSchema>;

/**
 * Branching predicate. The question is rendered only if `equalsAny` matches
 * the user's answer to `questionId`. Currently only "show when previous
 * answer is in this set" — sufficient for the v1 cold-chain branch.
 */
export const ShowWhenSchema = z.object({
  questionId: z.string().min(1),
  equalsAny: z.array(z.string().min(1)).min(1),
});
export type ShowWhen = z.infer<typeof ShowWhenSchema>;

export const RubricQuestionSchema = z.object({
  id: z.string().min(1).max(60),
  category: CategoryIdSchema,
  prompt: z.string().min(8).max(280),
  helpText: z.string().max(360).optional(),
  type: z.literal("single-choice"),
  options: z.array(QuestionOptionSchema).min(2).max(5),
  /** Within-category weight, 0–1. Category sub-weights sum to ~1. */
  weight: z.number().min(0).max(1),
  /** Optional branching gate. */
  showWhen: ShowWhenSchema.optional(),
});
export type RubricQuestion = z.infer<typeof RubricQuestionSchema>;

/* -------------------------------------------------------------------------- */
/*  Rubric                                                                     */
/* -------------------------------------------------------------------------- */

export const RubricSchema = z.object({
  version: z.string().min(1).max(40),
  categories: z.array(RubricCategorySchema).min(3).max(10),
  questions: z.array(RubricQuestionSchema).min(8).max(20),
});
export type Rubric = z.infer<typeof RubricSchema>;

/* -------------------------------------------------------------------------- */
/*  Answers                                                                    */
/* -------------------------------------------------------------------------- */

export const AnswerMapSchema = z.record(z.string().min(1), z.string().min(1));
/** `{ questionId: optionId }` — flat, easy to serialize. */
export type AnswerMap = z.infer<typeof AnswerMapSchema>;

/* -------------------------------------------------------------------------- */
/*  Assessment output                                                          */
/* -------------------------------------------------------------------------- */

export const TrafficLightSchema = z.enum(["green", "yellow", "red"]);
export type TrafficLight = z.infer<typeof TrafficLightSchema>;

export const CategoryScoreSchema = z.object({
  category: CategoryIdSchema,
  /** 0–100, normalized within-category. */
  score: z.number().int().min(0).max(100),
  trafficLight: TrafficLightSchema,
});
export type CategoryScore = z.infer<typeof CategoryScoreSchema>;

export const GapSchema = z.object({
  category: CategoryIdSchema,
  /** Short headline — e.g., "Site Master File not authored". */
  headline: z.string().min(4).max(160),
  /** One- or two-sentence description of why this matters for a DEL. */
  description: z.string().min(8).max(480),
});
export type Gap = z.infer<typeof GapSchema>;

export const RemediationItemSchema = z.object({
  /** Display priority, 1 = most urgent. */
  priority: z.number().int().min(1).max(20),
  /** What to do — imperative, plain language. */
  action: z.string().min(8).max(240),
  /** Why it matters now — references the gap it addresses. */
  rationale: z.string().min(8).max(480),
  /** Coarse effort signal so the user can scope a plan. */
  effort: z.enum(["small", "medium", "large"]),
});
export type RemediationItem = z.infer<typeof RemediationItemSchema>;

/**
 * Full assessment payload. The client renders this on the results screen.
 *
 *   - `score` + `categoryScores` are computed deterministically by
 *     `score.ts`. The model never emits them.
 *   - `gaps` + `remediation` come from the model's tool call.
 */
export const AssessmentSchema = z.object({
  rubricVersion: z.string().min(1),
  /** 0–100 overall readiness score. */
  score: z.number().int().min(0).max(100),
  /** Top-level traffic light derived from `score`. */
  trafficLight: TrafficLightSchema,
  categoryScores: z.array(CategoryScoreSchema).min(3),
  /** AI-generated. Empty array allowed when no gaps surface. */
  gaps: z.array(GapSchema).min(0).max(20),
  /** AI-generated. Sorted by priority. */
  remediation: z.array(RemediationItemSchema).min(0).max(20),
});
export type Assessment = z.infer<typeof AssessmentSchema>;

/**
 * Sub-shape the model is asked to fill via tool calling. Score + traffic
 * lights are computed server-side and merged in the route — the model only
 * supplies the qualitative analysis.
 */
export const AssessmentRecommendationSchema = z.object({
  gaps: z.array(GapSchema).min(0).max(20),
  remediation: z.array(RemediationItemSchema).min(0).max(20),
});
export type AssessmentRecommendation = z.infer<
  typeof AssessmentRecommendationSchema
>;
